### ISSUE TITLE
[Request]support to Avaritia mod and Extended Crafting mod

### ISSUE THREAD

**Issue by hyygybs** [vindocel/Dark-Mode-Everywhere-Fix#51]
https://www.curseforge.com/minecraft/mc-mods/avaritia-1-10
https://www.curseforge.com/minecraft/mc-mods/extended-crafting

**Comment by vindocel** [comment]
I will try to implement

**Comment by vindocel** [comment]
implementation done, now just wait for the 1.4.6 compilation | https://github.com/vindocel/Dark-Everywhere/commit/02a450e4b3a47f1ac7caf48449fa67075ff88e1d
