### ISSUE TITLE
[Request]support to Simply Jetpacks 2 mod

### ISSUE THREAD

**Issue by hyygybs** [vindocel/Dark-Mode-Everywhere-Fix#52]
https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2

**Comment by vindocel** [comment]
I will try to implement

**Comment by vindocel** [comment]
implementation done, now just wait for the 1.4.6 compilation | https://github.com/vindocel/Dark-Everywhere/commit/02a450e4b3a47f1ac7caf48449fa67075ff88e1d
