### ISSUE TITLE
Use shaders make all GUIs dark without specific support

### ISSUE THREAD

**Issue by RaptaG** [vindocel/Dark-Mode-Everywhere-Fix#57]
With new mods being added all the time, the pack is getting bigger and bigger and size.. There are people which never use _all_ the mods supported by Dark Everywhere. So, my suggestion is to use some sort of GUI shaders to darken all GUIs together, not separately.

If this is ever implemented, would it be compatible with Sodium?

**Comment by vindocel** [comment]
I even thought about this possibility, but I think that for a function like this the Mod Dark Mode Everywhere ([Forge](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere))([Fabric](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere-fabric)) does better

**Comment by RaptaG** [comment]
> I even thought about this possibility, but I think that for a function like this the Mod Dark Mode Everywhere ([Forge](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere))([Fabric](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere-fabric)) does better

Well, those are sadly not updated to 1.19.4, while Dark Everywhere is.
