### ISSUE TITLE
Issue with signs and maps

### ISSUE THREAD

**Issue by Viiekas** [vindocel/Dark-Mode-Everywhere-Fix#61]
When I enable the  texture pack all text from signs disappears and holding a map doesn't show anything, just empty hands.

Minecraft version is fabric 0.14.21-1.20.1 and I am using mostly performance enhancing mods with JourneyMap

![2023-07-30_23 41 46](https://github.com/vindocel/Dark-Everywhere/assets/140543313/a0921734-a7a3-4941-9c1d-5b9fed0de9d5)
![2023-07-30_23 41 56](https://github.com/vindocel/Dark-Everywhere/assets/140543313/3556d21b-d445-4777-be08-95e01fbeac1f)
![2023-07-30_23 42 16](https://github.com/vindocel/Dark-Everywhere/assets/140543313/b92e7644-7813-4dae-8079-1e44d56b565a)

**Comment by vindocel** [comment]
managed to replicate the same bug here, will be working to fix it, thanks a lot for reporting, the new update breaks a lot of the texture, decided to focus only on it from now on and discontinue texture updates for previous versions of minecraft

**Comment by vindocel** [comment]
https://github.com/vindocel/Dark-Everywhere/releases/tag/v1.4.7.3

FIX https://github.com/vindocel/Dark-Everywhere/commit/45d8c9b150e4f143718b14fcc84da6a840bbd28d
